### ISSUE TITLE
Adapter for neovim

### ISSUE THREAD

**Issue by benatouba** [dcermak/salt-lsp#17]
First of all, thank you so much for the work.

Is there an easy way, to get the ls working with neovim's [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).

I tried for a bit but could not get it to work.

It would be amazing if you had a quick tip.

**Comment by dcermak** [comment]
Unfortunately, I'm afraid that I don't have any great tips besides that you have to install the python package (either from git via `poetry build && pip install --user --force-reinstall dist/*whl` or from pypi) and then start the language server via `python3 -m salt_lsp`. That's what the emacs and vscode extension both do. Sadly, I'm not familiar with neovim at all, so I cannot really help you there a lot. I can only recommend to ask in the neovim chat channels (`#neovim` on either matrix or libera.chat), folks there are very nice and helpful.

**Comment by benatouba** [comment]
Thank you so much. that did work for me.
